### ISSUE TITLE
what video camera did you use? 

### ISSUE THREAD

**Issue by Vadimber2** [BeeAlarmed/BeeAlarmed#1]
Hello Fabian!

Very interesting project and I would like to deploy it for my apiary on Jetson Nano. Could you please share info about architecture and camera characteristic and manufacturer?

Thank you!
Best regards,
Vadim

**Comment by BeeAlarmed** [comment]
Hi Vadim,

the camera I use is a ELP-USB4KHDR01-MFV and the lens is from a Raspberry Pi HQ Camera 16mm. I added the lens with a custom made spacer, to get the best focus and resolution. The tracked area is roughly 13cm x 9cm and the camera is 30cm above the area.

Hope that helps, if you have any further questions, feel free to mail me at raspbee@posteo.de

BR
Fabian
