### ISSUE TITLE
Overtrained?

### ISSUE THREAD

**Issue by tot-ra** [BeeAlarmed/BeeAlarmed#7]
Hey Fabian & team. I'm trying to adapt and run the app. 
I got it working with the provided video, but with custom inputs seems like the detection rate and precision drops significantly.
Seems to me like it may be due to green background or maybe video resolution

upd. looks to be more sensitive to green background

https://github.com/BeeAlarmed/BeeAlarmed/assets/445122/2a8fa2b5-6b85-46c1-bd07-84d51a6e5ff9

**Comment by BeeAlarmed** [comment]
Hi tot-ra, 
first of all, thanks for your interesst in this project. 

It is not overtrained nor overfitted. Like most projects in the field of AI, it is highly optimized for the input material that I've used and it needs to be adapted to your inputs now. 

There is a three stage process: 
 1. Detect each bee in a video frame. This is done by using classical computer vision. It uses thresholds to seperate each bee from its background. This could have also been realized by using Object-Detection methods, but this approach was extremely fast and allowed real-time execution on a Jetson-Nano. Unfortunately, all the threshold and parameters were configured to work with my video material and with the green background. 
 2. Follow each bee from frame to frame, to records its movement
 3. Use AI to detect the bees characteristics. 

I suggest that you check the config.yaml and try to play arround with the 'Bee Detection' parameters. But without a homogeneous background and lighting this will not be easy. You can also display intermediate processing steps of the detection process, by modifying to code in https://github.com/BeeAlarmed/BeeAlarmed/blob/main/BeeDetection.py

BR 
Fabian
